# Creates a new image and push to Openshift image stream & also scan for vulnerabilities

name: Build and Push Updated Image to Openshift Registry & scan for vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  build-push-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@feature/devopsupgrade
    with:
      build_config_name: bc-paris-api
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}
      openshift_token: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
  
  trivy-scan-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/trivy-scanning-s2i.yml@feature/devopsupgrade
    needs:
      - build-push-image
    with:
      build_config_name: bc-paris-api
      imagestream_name: bc-paris-api
      source_image_tag: latest
    secrets:
      openshift_namespace: ${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools
      openshift_sa_name: ${{ secrets.OPENSHIFT_SA_NAME }}
      openshift_sa_password: ${{ secrets.OPENSHIFT_SA_PASSWORD }}
      openshift_external_repository: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
